### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/procrastinate#100]
For now, it's all fun and games, no one uses Procrastinate yet, and we haven't  really thought about migrations, but it's probably time to setup something.

- People might hop in and install procrastinate at any version (starting at 1.0, say)
- Starting from there, people will need to upgrade procrastinate (including the schema)
- Ideally, in a simple manner
- Ideally, without impact and downtime
- Optionally, using https://github.com/peopledoc/septentrion/ given we're developing this tool too.

One way of doing it could be:
- Adapt the migration files to septentrion. Remove `procrastinate migrate` in favor of `septentrion migrate`.
- Create a first migration for something trivial, just to test it.
- Document the hell out of it, so that it's easy to understand. Don't forget Septentrion is by far not as properly documented 1. as it should be and 2. as procrastinate is.
- (make it easy for people who want to read migrations instead of executing them)

(Note that in PeopleDoc, we actually don't need this part at all, because our fantastic DBA team will take care of the migrations for us, so this is strictly an effort to make procrastinate more usable by other people)

**Comment by ewjoachim** [comment]
Is it worth making a procrastinate cli command that spits out a septentrion.ini file ?

**Comment by ewjoachim** [comment]
Should `procrastinate` explicitely depend on `septentrion` (maybe using an extra) and `procrastinate migrate` be instead a wrapper around `septentrion migrate` that autoconfigures septentrion ?

**Comment by mgu** [comment]
I like the way that is described in the description :)
(plain sql files, septentrion as an extra requirement)

**Comment by ewjoachim** [comment]
@elemoine has come with a very very interesting proposal:

Given:
- Septentrion is not and has not been written to be a tool for running migrations in production
- Septentrion is very linked to PeopleDoc's way of writing migrations (including, for example, `--meta-psql:do-until-0`, etc)
- Septentrion is not as clean as Procrastinate is
- This is one of the last release blockers for 1.0
- There is an external tool (https://github.com/opengisch/pum/) that actually does what we wished Septentrion did.

Pum seems like a nice, much much more mature tool, with plenty of goodies.

Then, what about the following plan:

- We don't link Procrastinate to septentrion
- We publish up-to-date schemas, and a simple way to apply it ot an empty database
- We publish simple agnostic SQL migration files
- We advertise the use of pum in the documentation to use the migration files in real-life use cases

- Maybe, later, in a future that is not planned yet,we may self-migrate on startup using pum.
- Maybe, later, in a future that is not planned yet, we may add pum as an optional dependency and provide builtin task to self-migrate procrastinate (as long as we're not too far back, say 1 or 2 versions)

In the CI we could use pum too.

(Ping @elemoine @Evelf @DainDwarf )

@mgu ?

**Comment by k4nar** [comment]
Migrations will be a big concern for the community, but at PeopleDoc we'll handle them our way no matter what. So +1 to use a tool with a strong community for the greater good. It will be very easy for us to adapt internally.

**Comment by elemoine** [comment]
Closed by #161, #162, #163, #167, and #170.
