### ISSUE TITLE
Execute asynchronous tasks in parallel

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/procrastinate#106]
This is the third and last step in asynchronous compatibility.

- #9 is for defering jobs asynchronously
- #105 is for accepting a task to be a coroutine
- This ticket is for executing asynchronous tasks in parallel

For now, our tasks can be asynchronous, but there's still only one task executed at a time. We need a way to launch a pool of workers in the same event loop.
We need to check precisely where the right place is to place our pool. I don't know yet if we want 1 DB connection per process or per worker, and the potential impact on transactions. We'll probably need to setup a connection pool etc.

Note: we'll need some kind of ContextVar for the log context in Worker, because if we start parallelizing tasks, contexts will be ALL OVER THE PLACE. But ContextVar is py>=3.7 and we're supporting 3.6.

What if a worker that is setup to run parallel async tasks recieves a non-async task ? Should it run (and block all the other tasks running at the same time) or not run (but this breaks our model of never taking a task in the DB if we can't run it) ? To be determined before implementation.

Also we'll need to switch to a pool of pg connections, because one single connection cannot hold concurrent queries (we could have a specific parameter for concurrent pg connections vs concurrent workers)

**Comment by ewjoachim** [comment]
Thoughts:

We could just launch multiple workers the same way we do today but just launching multiple coroutines, each one managing their own independant connection. This means we'll need as many connections as we have workers, and it's far from ideal (maybe I want 100 workers that each do long tasks, I don't need 100 connections all the time).

Or

We could launch each worker and pass them the pool, and they'd acquire and release a connection only when they need it, but for listen/notify, we'll need a specific connection and keep it through time. This seems better.

<hr>

As we have it today, a call to `fetch` fetches 1 task if there's one in the queue, and returns `NULL` if there's no task to execute. A worker will call fetch until it gets NULL, and then wait for the connection.notifies. It's a bit special, because notifies is a [Queue](https://docs.python.org/3/library/asyncio-queue.html), but we're not interested in the payload, just in the event, and this means, if I understand correctly, that we should be using an [Event](https://docs.python.org/3/library/asyncio-sync.html#asyncio.Event). Even with a single worker, switching to an event would (probably drastically) reduce the number of fetch calls to the DB, because notifications accumulate in the notify queue, and we're only interested in the "next" one, not the ones already in the queue when we arrive. We'd need a coroutine like:
```python
async def queue_to_event(queue: Queue, event: Event):
	while True:  # or worker stop is requested
		await queue.get()  # or timeout
		event.set()
```
We would need this coroutine to run concurrently with actual worker(s). Workers need to call `event.clear()` and then `event.wait()`, so that they'll actually wait for the next event.

<hr>

So...
We'll switch to a Pool, and `asyncio.gather()` 1 "synchronizer" and n "single_worker" corountine. Each will run with a `while not stop requested`. The synchronizer will publish events, and the workers will read the event. Each worker will acquire and release connections only when they need so (a.k.a to fetch a task and to complete it). I think that inside workers, we never need a transaction, so that should work fine. To avoid problems, the synchronizer and each worker will timeout on their wait. This means the timeout parameter should be an app parameter, not a connector one.

**Comment by ewjoachim** [comment]
This is the kind of output we get:
```
╭ ➜ joachim@Picaboo.local:~/code/procrastinate [procrastinate] git:‹async-106› ✗
╰ ➤ procrastinate worker --concurrency 2
INFO:procrastinate.cli:Log level set to INFO
Launching a worker on all queues
INFO:procrastinate.worker.worker:Starting worker on all queues
INFO:procrastinate.worker.worker:Starting job procrastinate_demo.tasks.sleep[24](i=5)
INFO:procrastinate.worker.worker:Starting job procrastinate_demo.tasks.sleep[25](i=5)
INFO:procrastinate.worker.worker:Job success - Job procrastinate_demo.tasks.sleep[24](i=5) in 5.002 s
INFO:procrastinate.worker.worker:Job success - Job procrastinate_demo.tasks.sleep[25](i=5) in 5.001 s
INFO:procrastinate.worker.worker:Starting job procrastinate_demo.tasks.sleep[26](i=5)
INFO:procrastinate.worker.worker:Starting job procrastinate_demo.tasks.sleep[27](i=5)
INFO:procrastinate.worker.worker:Job success - Job procrastinate_demo.tasks.sleep[26](i=5) in 5.004 s
INFO:procrastinate.worker.worker:Starting job procrastinate_demo.tasks.sleep[28](i=5)
INFO:procrastinate.worker.worker:Job success - Job procrastinate_demo.tasks.sleep[27](i=5) in 5.002 s
INFO:procrastinate.worker.worker:Starting job procrastinate_demo.tasks.sleep[29](i=5)
^CINFO:procrastinate.worker.worker:Stop requested
INFO:procrastinate.worker.worker:Waiting for job to finish: worker 0: procrastinate_demo.tasks.sleep[28](i=5) (started 2.295 s ago)
INFO:procrastinate.worker.worker:Waiting for job to finish: worker 1: procrastinate_demo.tasks.sleep[29](i=5) (started 2.295 s ago)
INFO:procrastinate.worker.worker:Job success - Job procrastinate_demo.tasks.sleep[28](i=5) in 5.001 s
INFO:procrastinate.worker.worker:Job success - Job procrastinate_demo.tasks.sleep[29](i=5) in 5.005 s
INFO:procrastinate.worker.worker:Stopped worker on all queues
```

**Comment by lmwang9527** [comment]
With this ticket closed and #206 merged, the paragraph in the asynchronous howto document (https://github.com/peopledoc/procrastinate/blob/master/docs/howto/async.rst): "As of today, jobs are still executed sequentially" is no longer the case, correct? That is, asynchronous jobs are processed in parallel.

**Comment by elemoine** [comment]
@lmwang9527 good call. We'll fix that.

**Comment by ewjoachim** [comment]
Done, thank you !
