### ISSUE TITLE
Disable the "Warning task name different from python path" upon request

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/procrastinate#112]
It would be nice to provide a simple way to disable the warning that triggers everytime you define a task with a name that is not it's python import path. Of course, using a logging filter, people can already do that, but it lacks a bit of user friendliness. I'm thinking about a boolean parameter in `App.__init__()` ?

https://github.com/peopledoc/procrastinate/blob/81fe265a7a1865db77f93302cd82e8dcf9b22421/procrastinate/tasks.py#L83-L93

**Comment by marqov** [comment]
hi @ewjoachim !! can I work on this issue and procrastinate :smile: with you ?

**Comment by ewjoachim** [comment]
Absolutely, it would be a delight! There's already a bit of info on the issue, if you need anything, let me know !
