### ISSUE TITLE
Dockerize the procrastinate development environment

### ISSUE THREAD

**Issue by DainDwarf** [peopledoc/procrastinate#139]
To be able to quickly setup a development environment, we could wrap the procrastinate demo app in its own container in the `docker-compose.yml`. This would avoid the use all the exports in the `CONTRIBUTING.rst` and maybe some of the installs of the `README.rst`.

The new image should have the necessary variable to connect to the database and use the demo app, and its entrypoint should be the procrastinate command. Of course, it should bind the volume to the procrastinate directory and use a develop install, so that changes of code can be instantly checked on the demo app.

**Comment by ewjoachim** [comment]
It might also be a nice idea to make an official Docker image pushed on docker.com, and document a working docker-compose file :)
