### ISSUE TITLE
Wrap errors in aiopg connector

### ISSUE THREAD

**Issue by DainDwarf** [peopledoc/procrastinate#140]
Currently, database errors are raised from `psycopg2` or `aiopg`. However, we want to use our own errors, so that we have less dependancy with those librairies.

We need to catch all psyopg2/aiopg errors at the source so that we use our own custom-defined errors, with a `from` argument to not lose the base error.

This can probably be done inside a decorator that we apply on all `aiopg_connector` functions.

**Comment by ewjoachim** [comment]
`Contains: Some documentation`: We'll need to make sure that our custom exception is documented in the Reference section, and maybe drop a line in the "Discussions" about potential exceptions procrastinate can raise.
