### ISSUE TITLE
Procrastinate should be using a pool

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/procrastinate#148]
It just occured to me that we're not using an aiopg pool, but a connection directly. In the defer side, there may be hundreds of concurrent coroutines that try to defer at the same time. As of today, I think they will crash. We need a pool instead (which could very well be of size 1 if people don't want to create too many connections). Having a pool means aiopg manages the "semaphore" for us and we don't have to deal with it.

Who's in for a pool party ?
@elemoine / @k4nar: I believe this will be blocking for you quickly, so let's address that!

Also, we need a parameter to configure the pool size.
Finally, I'd advise against doing anything not based on top of #147.
(note: I have the beginning of a PR, but nothing that cannot be redone)

**Comment by ewjoachim** [comment]
Ok, I have a working branch up to the point of notifies, because a connection has a notify queue and a pool doesn’t which means we need to acquire a special connection and use it for synchronization.

I started doing that and it was a mess in the connector, a mess in the store and a mess in the worker. Then I realized:

The fact that, to us, the relevant primitive to model the listen/notify part is an
Event and not a queue tells us about the boundary api we should set.
The fact aiopg uses a queue is an implementation detail that should not be visible outside of the PostgresConnector.
This points towards implementing a `queue_listener` coroutine in the connector that recieves an Event and will:
- acquire a single connection
- listen on that connection for the appropriate channels
- wait on the notify queue
- set an event each time something happens

This will be much simpler to code and will allow removing some code from the store. It will make the isolation layer much more effective and will keep responsibilities much better segregated

**Comment by elemoine** [comment]
> It just occured to me that we're not using an aiopg pool, but a connection directly. In the defer side, there may be hundreds of concurrent coroutines that try to defer at the same time. As of today, I think they will crash.

What do you mean by "crash" here?

I do see a problem because coroutines will share the same transaction. But does fixing this really require using a connection pool? Couldn't we just do [`cursor.begin()`](https://aiopg.readthedocs.io/en/stable/core.html#aiopg.Cursor.begin) to create transactions? But maybe a connection pool is required for handling multi-threaded apps. (I hope that the aiopg pool implementation is thread-safe.)

**Comment by ewjoachim** [comment]
Oh, I'm definitely not advocating multithreading here. It might be worth stating this in the doc, but I really don't see the point in multithreading an async app.

Regarding cursor, I'm not sure what you meant:
```
import asyncio

import aiopg


async def coro(conn):
    async with conn.cursor() as curs:
        async with curs.begin():
            curs.execute("SELECT pg_sleep(5)")


async def main():
    async with aiopg.connect("") as conn:
        await asyncio.gather(coro(conn), coro(conn))


if __name__ == "__main__":
    asyncio.run(main())

```
```
  File "testpg.py", line 8, in coro
    async with curs.begin():
  File "/home/joachim/.virtualenvs/procrastinate/lib/python3.7/site-packages/aiopg/utils.py", line 94, in __aenter__
    self._obj = await self._coro
  File "/home/joachim/.virtualenvs/procrastinate/lib/python3.7/site-packages/aiopg/transaction.py", line 108, in begin
    await self._cur.execute(self._isolation.begin())
  File "/home/joachim/.virtualenvs/procrastinate/lib/python3.7/site-packages/aiopg/cursor.py", line 103, in execute
    waiter = self._conn._create_waiter('cursor.execute')
  File "/home/joachim/.virtualenvs/procrastinate/lib/python3.7/site-packages/aiopg/connection.py", line 183, in _create_waiter
    'data' % func_name)
RuntimeError: cursor.execute() called while another coroutine is already waiting for incoming data
```

?

**Comment by elemoine** [comment]
> Oh, I'm definitely not advocating multithreading here.

I am just saying that the application may be multi-threaded. Procrastinate offers an async API, as well as a non-async API that can be used by multi-threaded apps. So Procrastinate should be thread-safe and work with non-async, multi-threaded apps, such as Flask apps for example. No?

**Comment by k4nar** [comment]
> I really don't see the point in multithreading an async app

It's actually used quite a lot, mostly to make file I/O operations async (cf https://github.com/Tinche/aiofiles). But I think this is besides the point.

---

Anyway, I don't know listen/notify and its handling in Procrastinate well enough, so I don't really have anything to add prior to the implementation. But I would be happy to review and test the PR :) .

**Comment by ewjoachim** [comment]
> It's actually used quite a lot, mostly to make file I/O operations async

Yes, of course, the IO itself is threaded, that's the whole point (and if it's not available as non-blocking, then a thread calling locking calls will be conceptually equivalent), but if my understanding is correct, asynchronous IO already takes care of threading anything that might give you benefits. Threading manually on top of that would serve no purpose, no ?

It's kind of the same how Django has started implementing async, with the sync_to_async and async_to_sync functions that will launch sync things in threadpools and all. On an async application that doesn't do sync IOs, multithreading is useless (or I have misunderstood a lot of how async works, which is definitely a possibility)

**Comment by ewjoachim** [comment]
> So Procrastinate should be thread-safe and work with non-async, multi-threaded apps, such as Flask apps for example. No?

Hm, that is definitely a good point :/
Without talking about pools or what, I have no idea how even basic asyncio stuff work in a threaded environment. What does these lines will work ?
https://github.com/peopledoc/procrastinate/blob/b18f978fba7b1c028f1bafce047f4bfc0c5695b7/procrastinate/utils.py#L91-L92

Will we get an error when trying to access the event loop from a different thread ? Will we end up with multiple event loops ? What will be the impact ? This is uncharted territory.

**Comment by elemoine** [comment]
> Will we get an error when trying to access the event loop from a different thread ?

Yes, because [`asyncio.get_event_loop()`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_event_loop) creates a new event loop only if the current thread in the main thread.

**Comment by ewjoachim** [comment]
Ok, so as of now, we're not compatible with multithreading apps, and this has nothing to do with aiopg.

Let's create an issue to deal with that. Depending on the solution, maybe we'll find a good way. Maybe we'll just never support multithreading and only multiprocessing.
