### ISSUE TITLE
Pass context to running task

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/procrastinate#153]
Instantiate an immutable Context object in the worker, with the following attributes:
- job id
- worker name
- queue name
- task name
- lock
- attempts

Pass it as first argument to the task if the task was created with `pass_context=True` (False by default)

**Comment by k4nar** [comment]
Note that the Worker now has a handy `current_job_context` property, but there is no way to get the current Worker from a running task, or even from the App.

**Comment by ewjoachim** [comment]
Hm, yeah, not sure I really want to use that, especially when we'll start having multiple async mini-workers per worker.
