### ISSUE TITLE
Postgres image now requires `POSTGRES_PASSWORD`

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/procrastinate#176]
Source: https://github.com/docker-library/postgres/pull/658#pullrequestreview-336007842
> This is a breaking change, but I think it's one that makes sense overall (and that the benefit outweighs the pain in this instance).

We need to add a password in `docker-compose.yml` and make sure it is passed properly in the contribution doc (`CONTRIBUTING.rst`)

**Comment by ewjoachim** [comment]
@charlesaracil-ulti up for it ?

**Comment by charlesaracil-ulti** [comment]
@ewjoachim of course !

**Comment by ewjoachim** [comment]
Closed by #177
