### ISSUE TITLE
Rename PostgresConnector to AiopgConnector

### ISSUE THREAD

**Issue by elemoine** [peopledoc/procrastinate#186]
This issue suggests renaming PostgresConnector to AiopgConnector, for a more explicit class name. And we may want to add Psycopg2Connector or AsyncpgConnector in the future.

**Comment by k4nar** [comment]
The main downside I can see with supporting multiple libs is that if we don't make one "the official one", `pip install procrastinate` won't be enough to install Procrastinate on its own.

I guess we only have two options here:
- Choosing an official connector (AiopgConnector for now, as it's the only one :) ), and requiring the corresponding dependencies by default
- Or explicitly telling people to choose an extra dependency when installing Procrastinate

I think I have a favor for the second one, as forcing people to install dependencies they don't need doesn't seem like a good idea. Especially big binary dependencies like DB drivers.

**Comment by ewjoachim** [comment]
(the 3rd possibility which I don't support but would be possible is to manage each backend in its own package)

We'll need a dedicated error message when we import and it fails.
If possible, I'd like to avoid too much code running at import time.

**Comment by elemoine** [comment]
I am also in favor of option 2 (tell people to choose an extra dep when installing Procrastinate). But no need for this extra dep until we support another driver I guess.
