### ISSUE TITLE
Don't lose tasks when changing their path

### ISSUE THREAD

**Issue by mgu** [peopledoc/procrastinate#193]
By default, the name of a task is the full dotted path of the decorated function.

If we have to refactor our code and move that function, the name will change and the jobs in queue won't be able to be executed after the deployment of the new code.

Could we add the possibility for a function to have multiple names (or aliases) in order to  implement safe code upgrades ?

**Comment by elemoine** [comment]
Don't **named tasks** already provide that? See the `name` argument to the `@task` decorator: https://procrastinate.readthedocs.io/en/latest/reference.html#procrastinate.App.task.

**Comment by mgu** [comment]
I would have the same issue if I changed the name, how to handle the "migration" ?

**Comment by ewjoachim** [comment]
> Don't named tasks already provide that?

No, in order for users to implement any kind of name change for tasks safely, we need to support multiple names for a task. I think it's not unreasonable.

**Comment by elemoine** [comment]
@ewjoachim @mgu yep, I had misunderstood the initial issue/request.

**Comment by k4nar** [comment]
Maybe we could add an optional `previous_name` or `legacy_name` argument to the task decorator? Then procrastinate would look at tasks with both names.

**Comment by ewjoachim** [comment]
Hm, I was thinking of an `alias` iterable, where one could put several names.

I don't know how people plan to use ETAs but if they schedule a task a month or a year in advance, they may be glad if the task survives multiple refactorings :)

**Comment by tmartinfr** [comment]
Ok if the new parameter is used like this : `@app.task(name="b", aliases=["c", "d"])` (with `aliases` being an optional list or tuple) ?
Or do you prefer to have the possibility to also pass directly a string if there is only one alias (`@app.task(name="b", alias="c")` being the same as `@app.task(name="b", alias=["c"])`) ?

**Comment by ewjoachim** [comment]
Both would be fine to me, but if we only take a list, it should be called « aliases »
