### ISSUE TITLE
Notify after a locked task (?)

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/procrastinate#213]
We could do the following:

- When a task with a lock is finished
- And other tasks exist with the same lock
- Then a "NOTIFY" should occur because a task that was unavailable is now available (same as if it was deferred)

This would have the following consequences:

- Other worker can get a chance to grab the newly available task

Not doing this would have the following consequences:

- It's usually always the worker that finished the task that will be first to get the next task sharing the same lock.

Now the real question: is the current implementation a bad thing ? I guess it may lead to improper load balancing between workers, but... Is that bad ? Is that even true ?

**Comment by elemoine** [comment]
We can discuss it further but I think the current behavior is fine. It kinda makes sense that tasks to be executed sequentially actually execute on the same worker. Affinity is often good for performance. And in this case load balancing only makes sense if there are other tasks with no locks or with other locks.

**Comment by ewjoachim** [comment]
Well, we'll have considered the question.

If anyone wants to step up, it's very ok. Just reopen the ticket.
