### ISSUE TITLE
Codecov migration to marketplace app

### ISSUE THREAD

**Issue by thomasrockhu** [peopledoc/procrastinate#228]
Hi, Tom from [Codecov](https://codecov.io) here.

We noticed that you are using Codecov with fairly high frequency, and we’re so excited to see that! However, because you are not using our app, you may have experienced issues with uploading reports or viewing coverage information. This is due to rate-limiting issues from GitHub.

**In order to prevent any future outages, we ask that you move over to our [GitHub app integration](https://github.com/apps/codecov).**

The process is extremely simple and shouldn’t require more than a few clicks, and you should not expect any downtime. By moving to our app, you will no longer need an admin or separate account to manage the relationship with GitHub as the team bot.

Let me know if you have any questions, or if I can help at all with this process.

**Comment by ewjoachim** [comment]
@mgu I've done something but the GitHub UI is unclear whether I've juste request the app or activated it. Can you look on your side ? Thanks :)

**Comment by thomasrockhu** [comment]
Hi @ewjoachim and @mgu looks good from our side!

**Comment by mgu** [comment]
perfect, thank you :tada:

**Comment by ewjoachim** [comment]
Just want to say: @thomasrockhu that is some serious commitment to a great user experience and support. Congratulations to you and your team.

And have an excellent day !

**Comment by thomasrockhu** [comment]
Thank you so much @ewjoachim for your kind words! I really appreciate it, and we hope to be able to continue to improve and support you better. Feel free to reach out if there's anything we can be doing.
