### ISSUE TITLE
Comments regarding the "maxsize" pool argument

### ISSUE THREAD

**Issue by elemoine** [peopledoc/procrastinate#241]
Currently we force "maxsize" to be at least 2:

https://github.com/peopledoc/procrastinate/blob/4a726b0d74e70026c29606d1c165ec55ce3c9c77/procrastinate/aiopg_connector.py#L128-L129

Two comments about this:

1. There are applications where the "defer" code base and the "worker" code base are separate. And one may want to use `maxsize=1` on the "defer" side
2. And `maxsize=1` on the "worker" side may even make sense, when one wants to avoid leaving open connections after the "fetch_job" and "finish_job" operations

This second use-case is of interest for my application. We use 2 worker servers, with 8 workers per server. So with maxsize=2 this means 32 open connections all the time. With maxsize=1 it would be mean 16 open connections.

**Comment by ewjoachim** [comment]
I'm ok with 1, we could remove the max here and add a check in listen_notify() instead, which would crash if there's one connection

Regarding item #2, you need 1 connection for listen and notifies. If the pool has max 1 connection, then there's no connection left for fetching jobs.

**Comment by elemoine** [comment]
> Regarding item # 2, you need 1 connection for listen and notifies. If the pool has max 1 connection, then there's no connection left for fetching jobs.

A pool actually works with maxsize=0. It just doesn't reuse connections.

**Comment by ewjoachim** [comment]
Also, I'm not sure 2 connections per process is a very high number, especially given we would expect aiopg to shrink the pool when unused. Sadly, it seems it does not (https://github.com/aio-libs/aiopg/issues/309).

I think your usecase looks more like a pgpool usecase than a procrastinate usecase :) The high number in your setup is the number of procrastinate processes (16), not the number of connections per process.

> A pool actually works with maxsize=0. It just doesn't reuse connections.

Indeed this is a legitimate use case. (A bit dangerous, given aiopg seems to never close connections in a pool but hey, who am I to judge)

**Comment by ewjoachim** [comment]
So:
- Don't override the maxium at instantiation time
- Crash if listen_notify() is launched and the pool max size is 1 (specifically 1, 0 is ok, and >=2 is ok)

This won't change anything to your problem of your 16 worker processes taking 32 connections, but I still don't have an idea how to solve this.

**Comment by elemoine** [comment]
> A pool actually works with maxsize=0. It just doesn't reuse connections.

I got that wrong. `maxsize=0` is actually the same as `maxsize=None`, meaning that the pool is not limited.

**Comment by ewjoachim** [comment]
Ah, yes, I thought that was what you meant :D

**Comment by elemoine** [comment]
> (A bit dangerous, given aiopg seems to never close connections in a pool but hey, who am I to judge)

And `pool_recycle` may be used to make the pool close connections that have been idle for some time.
