### ISSUE TITLE
Switch to GitHub Actions

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/procrastinate#287]
### Rationale

Reasons to leave Travis:
- The whole travis.org / travis.com is, as far as I can tell, quite a mess
- The back and forth when I was trying to get the config working quite turned me away

Reasons to choose GitHub Actions:
- Supports Windows (as far as I can tell) and it appears we may have our first Windows users so maybe it's better if the CI can test Windows.
- We already have release drafter
- As far as I can tell, if we make a working pipeline, we might be able to factor it in other repos.

Things that are not a reason but might count still:
- Seems fun and I'd like to learn more about GH Actions.

Things to look for:
- The new CI should be simple to maintain and understand.
- In particular, the deployment is really simple, so I wish it can stay as simple.

Alternatives:
- CircleCI ? 

### What needs to be done:

On PR push and/or branch push, run either on the branch HEAD or the merge commit:
- tox: all python versions
- check-lint
- docs
- Maybe docs-spelling BUT only if it's not hard to run, if it doesn't change the current results and if it doesn't keep from merging (I don't want this to be a barrier to contribution)

On PR merge: release drafter (already present)

On tag push: release and twine upload

**Comment by elemoine** [comment]
Dropping this here, just in case: https://hynek.me/articles/python-github-actions/
