### ISSUE TITLE
PeriodicDeferrer should continue to work even when all workers are busy

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/procrastinate#292]
Imagine a setup with:
- A single worker
- Only sync tasks
- Most tasks are short, but 10% of the tasks take 30 minutes (so it's likely that ~100% of the worker time is spent on those tasks)
- There's a periodic task that should run every minute.

Given the only worker is almost always busy with the long task, the execution of the periodic job will have to wait and that's normal. What not normal is that the deferring of those tasks also has to wait, and moreover, when it happens, only the last missed task will be deferred. We expect that all 30 jobs would be deferred in between long tasks, each with their own unique timestamp.

So I'm not saying the PeriodicDeferrer should run in another thread, but when it hasn't run because of long tasks, it should consider ALL missed periods, not just the latest one.

There's an argument to be made on whether the MAX_DELAY (10 minutes) should be respected here or not. I think not, because it's not about running tasks for the current period at startup, here, it's deferring tasks that absolutely should have been deferred if internally, procrastinate wasn't running on an async event loop while still allowing for long tasks that will block the loop.

Alternatively, sync tasks could be ran asynchronously in a separate thread, but this raises a LOT of thread safety potential issues, but it could be a whole different way of solving the issue, a way that might make things much easier.

https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor

**Comment by elemoine** [comment]
In our application we use periodic tasks (currently through UNIX cron) for healthchecks. And we also use a queueing lock to prevent inserting a healthcheck job when there already is one waiting in the queue. With what you're proposing above it sounds to me that the Procrastinate periodic tasks would no longer work for us.

**Comment by ewjoachim** [comment]
- through the UNIX cron it would continue to work
- through the procrastinate periodic deferrer, it would work too, just the same.

Maybe I missed something but as far as I can tell, my proposition is not impacting your usecase at all

**Comment by elemoine** [comment]
>     * through the UNIX cron it would continue to work

Yes sure, but we've been considering switching to a Procrastinate periodic task.



>     * through the procrastinate periodic deferrer, it would work too, just the same.

Currently, with the use of a queueing lock, we cannot have more than one healthcheck job waiting in the queue. With your proposition, as I understand it, the worker would defer 30 healthcheck jobs after the 30 minute-long sync task has complete. Which would result in a burst of 30 healthchecks, which is exactly what we prevent from happening today, by relying on a queueing lock.

**Comment by ewjoachim** [comment]
I think the problem you describe is already present in the current code, and my proposal shines light on it, but doesn't really change it. In today's situation, if you have at least one active worker, then all the tasks will be deferred. If a worker is on a long task, then when it's done, all the deferred tasks will be executed.

The periodic lock and the fact the periodic deferrer doesn't defer old tasks should not be used as a poor man's defer lock, IMHO. If we want periodic tasks to use defer locks, we should implement proper defer locks.

Rereading it, what I said may not be exact, because you said your different workers defined the same task differently (each worker says the default task queue is the worker name) so each worker only executes its own tasks AND each worker ALSO only defers its own task. In that sense, I understand your concern, but I hold to my conclusion above.

**Comment by elemoine** [comment]
I think I agree with everything you said.

So for my team to be able to use Procrastinate periodic tasks we need to add support for queueing locks to periodic tasks.

**Comment by k4nar** [comment]
Maybe we could simply suggest to run periodic tasks in a dedicated worker (with a proper queue) when missing an occurrence is an issue? It doesn't solve the case where a periodic task must not run at the same time than a long running task, but I don't see how this could be solved anyway.

**Comment by ewjoachim** [comment]
> Maybe we could simply suggest to run periodic tasks in a dedicated worker (with a proper queue) when missing an occurrence is an issue?

Yeah but this means more specialized workers, which can be harder to deploy. It's much much easier if all the workers are identical.

> It doesn't solve the case where a periodic task must not run at the same time than a long running task, but I don't see how this could be solved anyway.

If we have tasks that should run at the same time, that's exactly what (serial) locks are for.
