### ISSUE TITLE
Run the "main" workflow for other branches than "master"

### ISSUE THREAD

**Issue by elemoine** [peopledoc/procrastinate#303]
We currently use https://github.com/peopledoc/procrastinate/blob/92f0fa63f9b1e923972d187badcc408a17af54e8/.github/workflows/main.yml#L3-L6

in our GitHub Actions CI workflow.

Meaning that we only run the CI workflow on "push" events to the master branch.

I am opening this issue to discuss generalizing this to all branches. In this way the CI workflow would run when people push to their feature branches, and before opening a PR. This may make even more sense for external contributors who use their own fork of Procrastinate.

**Comment by ewjoachim** [comment]
I think both work. If we run the CI twice, I'd like it better if it would run both on HEAD and on the merge commit of HEAD and the target branch.

Or did you mean also not run on PR and just run on branches ?

**Comment by ewjoachim** [comment]
What would be the equivalent of what Travis used to do ?

**Comment by thomasperrot** [comment]
Travis used to build:
- all branches
- all tags
- all pull requests

And when we push to a branch that has a pull request associated, it runs CI for both the branch and the pull request. 

To be consistant with what travis used to do, we should allow all branches to trigger CI, with: 

```
 on: 
   push: 
     branches: 
       - '*'
```
