### ISSUE TITLE
Do not use black>=20.8b0 for the moment

### ISSUE THREAD

**Issue by thomasperrot** [peopledoc/procrastinate#304]
The last versions of black, `20.8b0` and `20.8b1` contain a bug that breaks our linting. See https://github.com/psf/black/issues/1649. We need to use the most recent version BELOW 20.8b0 for the moment.

**Comment by ewjoachim** [comment]
I don’t think this is a bug, I understand this as « black being finally able to implement the rule that previously stated that lists with a final comma should be multiline, lists without a final comma should be single line.

**Comment by elemoine** [comment]
The developer of Black does recognize that 20.8b0 introduced a bug. See https://github.com/psf/black/issues/1649#issuecomment-683327600.

**Comment by ewjoachim** [comment]
Well, he says it's part bug part feature, and I think the part this issue identifies as a bug is the part he identified as feature, no ?

**Comment by ewjoachim** [comment]
(I have yet to be convinced that we're affected by what he recognized was a bug)

**Comment by elemoine** [comment]
I read more about Black's "magic trailing comma" feature, and re-read https://github.com/psf/black/issues/1649#issuecomment-683327600 one more time. And I think you're right @ewjoachim. So we need to reformat our code with Black 20.8b0 and probably use `>=20.8b0` as the classifier for Black.
