### ISSUE TITLE
Document how to make "remove_old_jobs" periodic

### ISSUE THREAD

**Issue by elemoine** [peopledoc/procrastinate#312]
It is currently not obvious to make the builtin "remove_old_jobs" task periodic. We need to improve the docs for this.

Hint:

```py
@app.periodic(...)
@app.task(queuing_lock=..., use_context=True)
async def remove_old_jobs(context, timestamp):
    return await app.builtin_tasks["remove_old_jobs"](context=context, ...)
```

**Comment by ewjoachim** [comment]
Another solution could be to add a method to App or to app.builtin_tasks dedicated to schedule periodic running of builtin tasks, but then one would need to provide:
- The schedule
- The task meta parameters (lock, queueing lock, queue, ...)
- The task parameters

That seems like an awful lot of things to pass. The proposition above seems not that complicated in comparison.
