### ISSUE TITLE
Raise an error when finish_job is called on a job whose status is not "doing" 

### ISSUE THREAD

**Issue by elemoine** [peopledoc/procrastinate#331]
The SQL query used by `JobStore.finish_job` increments the job's `attempts` value. So this method shouldn't be called on jobs whose current status is not `doing`, and we probably want to raise an error when the job doesn't have the status `doing`. We may even want to enforce the at this SQL level.

**Comment by ewjoachim** [comment]
While we're at it, we should also check that the destination state is either succeeded or failed, not todo or doing

**Comment by elemoine** [comment]
> While we're at it, we should also check that the destination state is either succeeded or failed, not todo or doing

Yes, I did that too.
