### ISSUE TITLE
Split the procrastinate_finish_job SQL function into two functions

### ISSUE THREAD

**Issue by elemoine** [peopledoc/procrastinate#332]
The `procrastinate_finish_job` SQL function looks like this currently:

https://github.com/peopledoc/procrastinate/blob/f831565b00d67afa7a4291d734c8fe85074a360c/procrastinate/sql/schema.sql#L175-L185

`scheduled_at` only makes sense for retries.

So @ewjoachim and I suggest that we split this function into two functions:

```sql
CREATE FUNCTION procrastinate_finish_job(job_id integer, end_status procrastinate_job_status) RETURNS void
    LANGUAGE plpgsql
    AS $$
BEGIN
    UPDATE procrastinate_jobs
    SET status = end_status,
        attempts = attempts + 1
    WHERE id = job_id;
END;
$$;

CREATE FUNCTION procrastinate_retry_job(job_id integer, retry_at timestamp with time zone) RETURNS void
    LANGUAGE plpgsql
    AS $$
BEGIN
    UPDATE procrastinate_jobs
    SET status = 'todo',
        attempts = attempts + 1,
        scheduled_at = retry_at
    WHERE id = job_id;
END;
$$;
```

And call the appropriate function from the worker code.

**Comment by ewjoachim** [comment]
BTW, it would be great if the increment part could be handled by a trigger. That would avoid mistakes and help the data be consistent.

**Comment by ewjoachim** [comment]
Note: solving this will lead us to the right direction for solving #307 .
