### ISSUE TITLE
New rules for migrations

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/procrastinate#341]
See #100 for our first iteration.

## Why

We need to provide a way to run migrations while procrastinate runs, which means we need each each version of the schema to be compatible with 2 at least versions of the code (and likewise, each version of the code to be compatible with at least 2 versions of the schema).

## How

- By setting clear rules on what version of the schema should work with what version of the code
- By testing that it's the case
- By documenting the upgrade strategy

We can be quite limiting at start (e.g. only upgrading versions 1 by 1 is supported)

Let's flesh out proposals below.

**Comment by ewjoachim** [comment]
# Proposal 1: "one by one" & calendar based releases

We guarantee that each DB version is compatible with procrastinate's previous codebase. This means that in a single version, we can always run the migrations for the next version.

High availability upgrade strategy for X to Z:
- Upgrade DB from X to Y
- Upgrade code from X to Y
- Upgrade DB from Y to Z
- Upgrade code from Y to Z
 
This means that if you need to upgrade 10 versions at once, you'll need 20 upgrade steps. In order to limit the steps, we should be avoiding making new versions that modify SQL too often. Thus we suggest adopting a calendar-based release with monthly releases.

**Comment by ewjoachim** [comment]
# Proposal 3 : Proposal 2 but checkpoint is X.99

We guarantee that each release within a major version X is compatible with the database at version X.99 (the "checkpoint" version).
We guarantee that each X.99 release is compatible with the database at version X+1.99

High availability upgrade strategy for X.5 to Z.5:

- Upgrade DB, then code from X.5 to X.99
- Upgrade DB, then code from X.99 to Y.99
- Upgrade DB, then code from Y.99 to Z.5

### What it means in terms of code:

- When we add a feature with a migration, we need to make sure that running this migration would not break the code on the first version of our current major, X.0
- If it does, we split into 2 parts: adding the messy-but-compatible migration on the current working version X and the cleanup on X+1.0
- The X.99 version doesn't need to introduce code, it can be identical to the previous one
- The X+1.0 version also doesn't need to introduce code, it just removes DB compatibility.
- We can also remove all previous migrations from the codebase on any X.0. We actually don't need to mark migration versions anymore.

**Comment by ewjoachim** [comment]
# Proposal 4 : Double checkpoints

We guarantee that each release within a major version X is compatible with the database at version X.99 (the "checkpoint" version).
We guarantee that each X.99 release is compatible with the database at version *X+1.0*

High availability upgrade strategy for X.5 to Z.5:

- Upgrade DB, then code from X.5 to X.99
- Upgrade DB, then code from X.99 to Y.0
- Upgrade DB, then code from Y.0 to Y.99
- Upgrade DB, then code from Y.99 to Z.5

### What it means in terms of code:

- When we add a feature with a migration, we need to make sure that running this migration would not break the code on X.0
- If it does, we split into 2 parts: adding the messy-but-compatible migration on the current working version X and the cleanup on X+1.0
- The X.99 version doesn't need to introduce code, it can be identical to the previous one
- The X+1.0 version also doesn't need to introduce code, it just removes DB compatibility with X-1.
- We can also remove all X-1 migrations from the codebase on any X.0.

**Comment by ewjoachim** [comment]
Discussing we @elemoine : we're going for proposition 3 but you have until `2020-10-23 08:00:00Z` to express concern :)

Ping @k4nar @mgu @marco44

**Comment by marco44** [comment]
2 or 3 for me, I'm fine with both. So I presume it's a vote for 3 too

**Comment by k4nar** [comment]
I think I'm ok with proposition 3, but I find the ".99" a bit confusing. Would formulating it this way work?
> We guarantee that each release within a major version X is compatible with the database at any release within the next major version (X+1).

**Comment by ewjoachim** [comment]
I'm not sure this would be true.
Imagine we remove a field at version 1.5, the code stops using it. At 1.99, there's still the field, but we know that it's not used anymore. At 2.0 we remove the field. This means the code at 1.99 is compatible with the db at 2.99, but the code at 1.4 is not.

We're talking about a real ".99" version that we'll be creating for real, each time we make a major release, in order to have a version you can use on a given major that you can be sure has the most updated code. This means upgrading from this 1.99 release to any 2.X release will be safe.

**Comment by k4nar** [comment]
Do you have examples of projects doing this? I find it very unusual. Plus when we'll make the .99, what tells us that we won't have another minor version to make?

I feel like there is a simpler option, but I can't get my head around it. I'm not sure it's Option 2 either.

**Comment by ewjoachim** [comment]
> Plus when we'll make the .99, what tells us that we won't have another minor version to make?

That would imply we would support older versions. I think the plan for now is just to support the latest one.

> Do you have examples of projects doing this? I find it very unusual. 

Do you have examples for non-django projects integrated as libraries into users project and that require SQL migrations ?

**Comment by ewjoachim** [comment]
Another proposal could be to postpone cleaning after X+2.0, which would lead to [your suggestion above](https://github.com/peopledoc/procrastinate/issues/341#issuecomment-713692938)

Note: proposal 2 is like proposal 3 without the .99, so that would work too.

**Comment by elemoine** [comment]
The advantage of proposal 3 (the "0.99" proposal) is that we don't need to wait for X+1.1 to remove the SQL code for backward compatibility. Instead we can do the clean-up directly in X+1.0.

So with proposal 3 we'd release X.99 just before releasing X+1.0. And we'd tell our users that they need to upgrade to the X.99 pivot version before upgrading to X+1.

With proposal 2 we'd release X+1.0, and  X+1.1 right after for the SQL clean-up. And we'd tell our users that they need to upgrade to X+1.0 before upgrading to any other X+1 version. We can also recommend that they upgrade from X+1,0 to X+1.1 as soon as X+1.1 comes out, although that's not required.

With that I mind I think I prefer proposal 2, because it'd be more natural and usual to our users. With proposal 3, when they are ready to upgrade to the next major version (from X.n to X+1.0), we would force them to do 2 upgrades, from X.n to X.99, and them from X.99 to X+1.0. With proposal 2, they can upgrade from X.n to X+1.0, and then, optionally, from X+1.0 to X+1.1.

@ewjoachim, what do you think? I can go ahead and document the migration process when we agree on the proposal.

**Comment by ewjoachim** [comment]
Frankly, I'm ok with anything as long as it's documented.

**Comment by elemoine** [comment]
Here is my first attempt at documenting this: https://github.com/peopledoc/procrastinate/pull/342.
