### ISSUE TITLE
Can't apply the schema in an `async with app` block

### ISSUE THREAD

**Issue by BracketJohn** [peopledoc/procrastinate#367]
As far as I understood, one needs to call `app.schema_manager.apply_schema()` from within the code at least once in order to initialize the database correctly.

In the `sync` variant, this works well. In the `async` variant, it does not work when using the context manager.

This works:
```py
await app.open_async()

app.schema_manager.apply_schema()

await app.close_async()
```

This does not work:
```py
await app.open_async()

await app.schema_manager.apply_schema()

# --> RuntimeError: This event loop is already running

await app.close_async()
```

And neither of the following works:
```py
async with app.open_async():
    app.schema_manager.apply_schema()

# --> RuntimeError: This event loop is already running

async with app.open_async():
    await app.schema_manager.apply_schema()

# --> RuntimeError: This event loop is already running

# ... after some time passes

#  RuntimeWarning: coroutine 'AiopgConnector.execute_query_async' was never awaited
#  self.mouse_handlers[x, y] = handler
#  RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

My first guess would be, that the problem comes from the `schema_manager` being purely sync, see https://github.com/peopledoc/procrastinate/blob/a8a7a50e5097026d924bb86cdf9838cdb3f83245/procrastinate/schema.py#L25.

A workaround that I'm currently using is to instantiate the schema `sync` and then switch to `async`.

**Comment by ewjoachim** [comment]
I think that while we wanted to expose `apply_schema` within the code to help people build their custom tool, the usual expected way of doing this is via the CLI: `procrastinate schema --apply`.

Also, you're right, if we want people to call this from async code, we'll need a `.apply_schema_async()`.

```python
    async def apply_schema(self) -> None:
        queries = self.get_schema()
        self.connector.execute_query_async(query=queries)
```

**Comment by ewjoachim** [comment]
Note that applying the schema this way is something to be done once. This command does not apply missing migration, it's means to install the full procrastinate schema on an empty database, so it's expected to fail on the 2 time you launch it. If you want to apply missing migrations, see https://procrastinate.readthedocs.io/en/latest/howto/migrations.html

(We meant to make this less theoretical and more practical, but if you have questions on this process, feel free to shout :) )

**Comment by BracketJohn** [comment]
> the usual expected way of doing this is via the CLI:

Understood, we might be a bit out of your scope then, as we're currently building a container based solution (probably around procrastinate, but that's still to be discussed, as you can see by my activity :D). In that scenario, it would be desirable to have _as little CLI as possible_.

Would you be open to a PR that adds an async schema manager?

**Comment by ewjoachim** [comment]
Yep definitely ! Please go ahead :)

**Comment by BracketJohn** [comment]
Took some time, but the PR is up :+1:
