### ISSUE TITLE
Is it safe to run multiple `procrastinate` instances on different machines?

### ISSUE THREAD

**Issue by BracketJohn** [peopledoc/procrastinate#369]
**Question**

For a use-case we'd like to launch `procrastinate` workers on multiple different machines. I worry a bit that since there will be multiple connection pools in that case, there's some problems regarding syncing/concurrency/... Are there any known problems on the use of multiple connector pools/connecting from multiple places to the same DB from your side?

Thanks!

**Comment by ewjoachim** [comment]
Hello, and thanks for opening an issue !

Having distributed workers on different machines is at the heart of how `procrastinate` is meant to be used. Sychronization & concurrency are managed by the [ACID](https://en.wikipedia.org/wiki/ACID) properties of your PostgreSQL Database.

**Comment by BracketJohn** [comment]
Awesome, thanks for the quick response (4 minutes!). Can you comment on how one would go about synchronizing `Task` definitions?

Say we want to have an API running on one server that is supposed to add jobs for multiple different `Task`s. How can we get the task definitions on the API side, so that it can add jobs for the different `Task`s? Do we need to re-declare the `@app.task` everywhere we want to add jobs?

**Comment by BracketJohn** [comment]
Ah, I found the solution to this myself. One can use `app.configure_task(name="some_task", queue="some_queue")` in order to defines tasks and defer jobs for them from some other place.

Thanks for your support, from my side this issue can now be closed.

**Comment by ewjoachim** [comment]
Yep exactly :) If you think this would deserve more documentation, please say so.

For reference, https://procrastinate.readthedocs.io/en/stable/howto/defer.html#defer-a-job-if-you-can-t-access-the-task
