### ISSUE TITLE
`InMemoryConnector` and `AiopgConnector` handle `queueing_lock=None` differently

### ISSUE THREAD

**Issue by BracketJohn** [peopledoc/procrastinate#372]
When writing tests, I noticed that the following works using the `AiopgConnector`:

```py
app = procrastinate.App(connector=procrastinate.AiopgConnector())

app.open()

app.schema_manager.apply_schema()

app.task(lambda x: x, queue='sum', name='sum').defer(x=1)
# -> 1

app.task(lambda x: x, queue='sum', name='sum').defer(x=2)
# -> 2
```

However, using the `InMemoryConnector` it does not:

```py
app = procrastinate.App(connector=InMemoryConnector())

app.open()

app.schema_manager.apply_schema()

app.task(lambda x: x, queue='sum', name='sum').defer(x=1)
# -> 1

app.task(lambda x: x, queue='sum', name='sum').defer(x=2)
# Raises -> "AlreadyEnqueued: Job cannot be enqueued: there is already a job in the queue with the queueing lock None"
```

As the exception states: Both jobs have `queueing_lock == None`, so they cannot both be deferred to the `queue`.

Is this behavior desired? For me it would make more sense if both would raise, since in both cases `queueing_lock == None`, independent of storage.

**Comment by ewjoachim** [comment]
Oh, you're right, it's a bug in the InMemoryConnector.

**Comment by ewjoachim** [comment]
The fix should be just changing this line:
https://github.com/peopledoc/procrastinate/blob/master/procrastinate/testing.py#L97

to:
```
	job for job in self.jobs.values() if queueing_lock and job["queueing_lock"] == queueing_lock
```
