### ISSUE TITLE
`InMemoryConnector` and `AiopgConnector` _still_ handle `queueing_lock` differently

### ISSUE THREAD

**Issue by BracketJohn** [peopledoc/procrastinate#378]
Follow up to https://github.com/peopledoc/procrastinate/issues/372 - we're only discovering these peu à peu as we're using the library.

### Bug description

For the database connector the following works:

1. enqueue job in queue `A` with queueing lock `B`
2. run worker on queue `A`, so that the job enters state `SUCCEEDED`
3. enqueue job in queue `A` with queueing lock `B`
4. ...

For the `InMemoryConnector`, this does not work:
1. enqueue job in queue `A` with queueing lock `B`
2. run worker on queue `A`, so that the job enters state `SUCCEEDED`
3. enqueue job in queue `A` with queueing lock `B`

-> Raises `AlreadyEnqueued`

### Bug source

The Database queueing lock is implemented using a unique index on `queueing_lock` with the additional check that `status = 'todo'` ([schema here](https://github.com/peopledoc/procrastinate/blob/master/procrastinate/sql/schema.sql#L57))

The Memory queueing lock implementation has a "unique index via `any` check" _without_ the additional check that `status = 'todo'` ([implementation here](https://github.com/peopledoc/procrastinate/blob/master/procrastinate/testing.py#L97))

### Fix

To fix this, the job `status` also needs to be checked, see #379

**Comment by ewjoachim** [comment]
oh, that's true...

I wonder if there would be an easy way to catch those beforehand.

**Comment by BracketJohn** [comment]
I think first unifying the in-memory connector API and aiopg connector API and then also merging all their test cases would give better assurances that both behave in the same way and that the `procrastinate` itself is _truly_ connector agnostic. 

To approach this one could first merge the test cases, leading to a lot of stuff breaking, and then adapt the connectors/other affected code.

That'll be a fair share of work though and of course there will be internal discussions/prioritization/non-goals that I'm now aware of.
