### ISSUE TITLE
Implement an administration prompt with cmd

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/procrastinate#38]
Python's standard lib has https://docs.python.org/3/library/cmd.html , which will help us implement easily an interactive prompt.

We could probably use the following features:
- List queues (and number of queued & processing jobs per queue, with stats like processing rate, average wait time etc.)
- List tasks (and ... same stats)
- List jobs & search for a specific job (by task, queue, lock, id, maybe args)
- List stalled jobs and error jobs

(it would be nice if those pages could stay on and autorefresh)
(also, use colors ?)

- Display a job, and provide specific actions: discard it, retry it (now or later), manually set it to success or failure (well it's all about changing the state of the job)
- Batch action ? 

And finally, the cmd prompt should just be an interface, and the real actions should be implemented independently in an `admin` module, because we'll probably have exactly the same needs for the API and/or the web admin panel.

**Comment by ewjoachim** [comment]
We'll need a migrate command too.

**Comment by entwanne** [comment]
Hi,

You mentioned cmd stdlib module, but also a possible support for colors.
I think autocompletion could be a great feature too.

Then I was thinking about [`prompt_toolkit`](https://github.com/prompt-toolkit/python-prompt-toolkit), do you think it's ok to depend on a thir-party lib for this?
Or maybe make the dependency optional?

**Comment by ewjoachim** [comment]
Yep, that looks nice.
We could have that as an optional dep, indeed, because I suspect even if one may want to use it, they may not want to install it both in "defer" and "worker" environments.

Also: it may be possible to skip that step entirely and go for a web-based admin (REST + js front ?)
