### ISSUE TITLE
Ambiguous PSQL function when `delete_job` undefined

### ISSUE THREAD

**Issue by BracketJohn** [peopledoc/procrastinate#381]
**Summary**

When `delete_job` of the current `procrastinate_finish_job` function is `None`, the current `procrastinate_finish_job`, [defined here](https://github.com/peopledoc/procrastinate/blob/master/procrastinate/sql/schema.sql#L203), becomes ambiguous with the old(est) one [defined here](https://github.com/peopledoc/procrastinate/blob/master/procrastinate/sql/schema.sql#L177).

**Trace**

The resulting bug looks like:
```sh
  File "aiopg/connection.py", line 106, in _ready
    state = self._conn.poll()
psycopg2.errors.AmbiguousFunction: function procrastinate_finish_job(integer, unknown, unknown) is not unique
LINE 1: SELECT procrastinate_finish_job(4, 'succeeded', NULL);
               ^
HINT:  Could not choose a best candidate function. You might need to add explicit type casts.

The above exception was the direct cause of the following exception:

[...]
 File "/procrastinate/worker.py", line 171, in process_job
    await self.job_manager.finish_job(
 File "/procrastinate/manager.py", line 135, in finish_job
    await self.connector.execute_query_async(
 File "/procrastinate/aiopg_connector.py", line 35, in wrapped
    raise exceptions.ConnectorException from exc
procrastinate.exceptions.ConnectorException: 
    Database error.
```

Sadly, I don't have a minimal example for reproduction at the moment. The error occured when starting one worker after a job was deferred.

A possible solution would be enforcing a boolean value of the `delete_job` param of  `finish_job`.

**Comment by ewjoachim** [comment]
Hey there, thanks for submitting the issue.

@elemoine you're much more versed than I am into the PG intricacies, if you want to give it a shot, I'll be glad, otherwise, I'll try and see :)

**Comment by elemoine** [comment]
@BracketJohn can you please tell what Procrastinate version your worker code uses? And what Procrastinate version you have for the database schema?

**Comment by BracketJohn** [comment]
Sure thing! Both used `v18.1`

**Comment by elemoine** [comment]
> Sure thing! Both used `v18.1`

So you are 100% sure the worker code uses v18.1? (and that it has been restarted to use that version of Procrastinate). Sorry for insisting.

**Comment by elemoine** [comment]
I insist :-)

v0.18.1 worker.py line 171 is [this](https://github.com/peopledoc/procrastinate/blob/0.18.1/procrastinate/worker.py#L171):
```
            status = jobs.Status.SUCCEEDED
```

v0.17.0 worker.py line 171 is [this](https://github.com/peopledoc/procrastinate/blob/0.17.0/procrastinate/worker.py#L171):
```
            await self.job_manager.finish_job(
                job=job, status=status, scheduled_at=next_attempt_scheduled_at
            )
```

So based on the trace you provided in the issue description it looks like your worker isn't on v0.18.1.

Note that I am not saying there isn't a problem on the Procrastinate side, I just want to know the exact versions you're using to make sure we fully understand the problem.

**Comment by BracketJohn** [comment]
I understand the need for insistence (: So, the first worker used v0.18.1, the second worker, the one that crashed, used v0.18.0.

I just tried to quickly come up with an example that can reliably reproduce this and I couldn't - however the colleague who first raised this and with whom I initially investigated is not available at the moment. So in order to be able to reproduce this it will sadly take til next week - sorry for that.

**Comment by elemoine** [comment]
v0.18.0 worker.py line 171 is [this](https://github.com/peopledoc/procrastinate/blob/0.18.0/procrastinate/worker.py#L171):

```
            status = jobs.Status.SUCCEEDED
```

So it looks like the worker wasn't on 0.18.0 either. It seems that it was on an older version of the Procrastinate code.

**Comment by elemoine** [comment]
So waiting for your confirmation… but I am already convinced that https://github.com/peopledoc/procrastinate/pull/354 broke our "service continuity" contract defined in https://procrastinate.readthedocs.io/en/stable/contributing.html#backward-compatibility.

**Comment by BracketJohn** [comment]
Will give an update here next week. Let's hope that the environment in question didn't change until then.

**Comment by BracketJohn** [comment]
As promised: We were able to confirm that one of the workers ran on v0.17.x and the other one on v0.18.x.

So, updating the other one solves the issue (: It was still there due to an outdated dependency in the virtual env.

**Comment by elemoine** [comment]
Thanks for confirming that the failing instance ran on v0.17.x. That makes more sense now. We'll see how we can fix that. Sorry for the trouble.

**Comment by BracketJohn** [comment]
Sure thing.

From our perspective no worries - migrating to `0.18` is no problem/was already done, just not locally. However, I do see that this may be a problem for others and for the contract you've defined.
