### ISSUE TITLE
Access app.connector from a worker

### ISSUE THREAD

**Issue by lmwang9527** [peopledoc/procrastinate#390]
I am not sure this is an appropriate place for questions like mine, as I haven't found a good place for procrastinate related questions - I apologize if it is not & please let me know, so I will move it to an appropriate place.

I want my workers to write results from completed jobs to a psql database - the same database initiated for the App connector. Is there a way for workers to access to app.connector from within a task function?

I have tried my best to search for sample code in the repository and the document and haven't found any. I also tried to pass app or an aiopg.Pool object to my task functions, but I am getting a "TypeError: Object of type Pool is not JSON serializable".

Related to this, what is the best way to pass an object like an aiopg.Pool that is to be shared across jobs and close it before all workers exit? Besides the connection pool, I hope to share aihttp.ClientSession across jobs and then close it before all workers exit. Is it possible?

At this point, I resort to pass the dsn to each job and have each worker create its own psql connection and aihttp.ClientSession. It works but is less than optimal. I like how the arq package (an async job queues with redis) accepts a startup & shutdown function to initiate & dispose resources that are to be shared across jobs (https://arq-docs.helpmanual.io/#startup-shutdown-coroutines). Is this something possible with procrastinate?

Thanks for creating this powerful package!

**Comment by elemoine** [comment]
@lmwang9527 please take a look at the `pass_context` argument in the [doc](https://procrastinate.readthedocs.io/en/latest/reference.html#tasks). When `pass_context` is `True` is the task declaration the task function receives a [`JobContext`](https://procrastinate.readthedocs.io/en/latest/reference.html#procrastinate.JobContext) instance as its first argument.

**Comment by ewjoachim** [comment]
Yep, I think JobContext can be a way to go, indeed.

> At this point, I resort to pass the dsn to each job and have each worker create its own psql connection and aihttp.ClientSession. It works but is less than optimal. I like how the arq package (an async job queues with redis) accepts a startup & shutdown function to initiate & dispose resources that are to be shared across jobs (arq-docs.helpmanual.io/#startup-shutdown-coroutines). Is this something possible with procrastinate?

Yes we could imagine a way of adding arbitrary info to the JobContext.

At this point, it's also worth considering storing common information a module-level variable. I agree that it's better to receive parameters than relying on a global variable, but it's a possibility :)

**Comment by lmwang9527** [comment]
Thank you both for your responses! it is exactly what I'm looking for. I did try using a module-level variable, but I cannot pass objects that cannot be serialized to my job function though. But the job_context would avoid having to do that.

Any recommendation what is the best way to close an object before all workers exit? For example, closing an aiohttp.ClientSession object I insert as an attribute to JobContext. I am getting an "Unclosed client session" warning if I don't call `await client_session.close` in my close before workers quit.

**Comment by ewjoachim** [comment]
As a temporary method, you could subclass `Worker`, overload `run` where you'd call `super()` and add your own logic here. You'd definitely be tapping on the private API, but it should work.

So to summarize, an API could be setting on the App an async context manager, that would `__enter__` when the worker is started, and return some context info that would be attached to the context for each task, and then the `__exit__` would be called when all the workers have stopped.

Right ?

**Comment by elemoine** [comment]
@ewjoachim how about the following?

```py
    async with app.open_async() as app:
        await app.run_worker_async(context={"http_session": http_session})
        http_session.close()
```

**Comment by ewjoachim** [comment]
yep, but that only works when launching the worker by hand, not by CLI. That being said, I'm ok with this too.

(we can already override the context in `run_worker` ? I had forgotten that !)

We may write the same as:
```python
async with app.open_async() as app:
	async with AsyncSession as http_session: 
    	await app.run_worker_async(context={"http_session": http_session})
```
or 
```python
async with app.open_async() as app, AsyncSession as http_session:
    await app.run_worker_async(context={"http_session": http_session})
```

**Comment by elemoine** [comment]
> (we can already override the context in `run_worker` ? I had forgotten that !)

No, that was more a proposal for a new argument to `run_worker_async`.

**Comment by ewjoachim** [comment]
then I'm good with that.

**Comment by lmwang9527** [comment]
Thanks again for your responses! That gives a direction to aim for. It'd be helpful if run_worker_async accepts a context argument - looking forward to its implementation.

**Comment by elemoine** [comment]
@lmwang9527 for your information, @ewjoachim and I have worked on a PR that makes it possible to define additional context for the tasks. See #392.

**Comment by lmwang9527** [comment]
Thank you so much for implementing the feature so quickly! I'm taking advantage of it and it works flawlessly.

**Comment by elemoine** [comment]
@lmwang9527 thanks, this is great feedback!
