### ISSUE TITLE
Cannot open procrastinate application in an async application

### ISSUE THREAD

**Issue by mecampbellsoup** [peopledoc/procrastinate#437]
We have a fast-api ASGI web application and are trying to use procrastinate as our Postgres-based task/queue management system.

I attempt to `App.open()` our procrastinate app so that I can e.g. `some_task.defer()` - however I am getting an error that the event loop is already running (not terribly surprising since that's what fast-api runs on):

```
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [1] using watchgod
INFO:     Started server process [9]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 526, in lifespan
    async for item in self.lifespan_context(app):
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 467, in default_lifespan
    await self.startup()
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 502, in startup
    await handler()
  File "/cloud-app/./app/main.py", line 43, in startup
    procrastinate_app.open()
  File "/usr/local/lib/python3.9/site-packages/procrastinate/app.py", line 330, in open
    self.connector.open(pool)
  File "/usr/local/lib/python3.9/site-packages/procrastinate/utils.py", line 118, in wrapper
    return sync_await(awaitable=awaitable)
  File "/usr/local/lib/python3.9/site-packages/procrastinate/utils.py", line 168, in sync_await
    return loop.run_until_complete(awaitable)
  File "uvloop/loop.pyx", line 1495, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1488, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 511, in uvloop.loop.Loop._run
RuntimeError: this event loop is already running.
```
We have separate processes (containers) for fast-api vs. procrastinate _workers_, but our fast-api container does seem to need to call `App.open()` in order to defer tasks to the queue, to ultimately be picked up by the worker(s).

Is my understanding correct?

UPDATE: It seems like this may be what `App.open_async()` is for; trying this now.

**Comment by elemoine** [comment]
@mecampbellsoup please read https://procrastinate.readthedocs.io/en/latest/howto/open_connection.html. I am going to close this, but feel free to reopen if you still have problems.

**Comment by mecampbellsoup** [comment]
@elemoine yes, thank you! I got this sorted out for the most part.

Now I'm trying to figure out how to launch my worker process with the ability to run some arbitrary code (e.g. my task definitions depend on a separate DB connection/interface than what procrastinate itself uses, so I need to `await database.connect()` so that my task implementations can run).

Is there any way to combine the CLI invocation `procrastinate worker --app=...` with something like this:

```python
from procrastinate import AiopgConnector, App

from app.settings import database, DATABASE_URL

app = App(
    connector=AiopgConnector(dsn=DATABASE_URL),
    import_paths=['app.reconciler'],
)


async def main():
    async with app.open_async():
        await database.connect()
        # Only needed if running the worker not via CLI invocation (just normal Python script)
        await app.run_worker_async(
            delete_jobs='successful',
        )
```

**Comment by mecampbellsoup** [comment]
Also FYI I cannot reopen the issue (if you think that is necessary I will just open a new issue).

**Comment by mecampbellsoup** [comment]
@elemoine https://github.com/peopledoc/procrastinate/issues/438 👍
