### ISSUE TITLE
Task/ Queue Priority

### ISSUE THREAD

**Issue by sebastian-hatala-leanix** [peopledoc/procrastinate#440]
For a use case of mine it would be great to have the option of "prioritising" certain tasks above others.

At a certain time on each day I have a set of tasks that are executed and take a while. During the time it takes to process these tasks, I might want to add a new task to be executed before any of the already queued tasks is started. Is this possible at the moment or is this something that would be considered?

Also, there is a workaround to add a dedicated worker for just these "high priority" tasks. But since the occurrence of such tasks is irregular the cost of having such a worker overweights the benefit in my eyes.

**Comment by ewjoachim** [comment]
Itg's a good idea, but it's a duplicate from https://github.com/peopledoc/procrastinate/issues/386 . Closing as such, but feel free to chime in over there :)
