### ISSUE TITLE
Simple Aiopgconnector Not working

### ISSUE THREAD

**Issue by nanotkarashish** [peopledoc/procrastinate#444]
I am trying to get procrastinate to work with my app but I am not able to run the simplest of the example mentioned on the official site.

Please guide me.

`import asyncio`
`from app.config.base import config`
`import procrastinate`

`worker_app = procrastinate.App(connector=procrastinate.AiopgConnector(dsn=config.db.postgres.database_url))`

Error details:
`C:\Users\nanot\Documents\projects\safemeet-api-py>procrastinate --app=pg_worker.worker_app schema --apply`
`Error:`
`Exception ignored in: <function Connection.__del__ at 0x000001F5942EB790>`
`Traceback (most recent call last):`
`  File "c:\programdata\miniconda3\envs\safemeet-api-py\lib\site-packages\aiopg\connection.py", line 1188, in __del__
    self.close()`
`  File "c:\programdata\miniconda3\envs\safemeet-api-py\lib\site-packages\aiopg\connection.py", line 995, in close
    self._close()`
`  File "c:\programdata\miniconda3\envs\safemeet-api-py\lib\site-packages\aiopg\connection.py", line 977, in _close
    self._loop.remove_reader(self._fileno)`
`  File "c:\programdata\miniconda3\envs\safemeet-api-py\lib\asyncio\events.py", line 504, in remove_reader
    raise NotImplementedError`
`NotImplementedError:`

**Comment by nanotkarashish** [comment]
Closed as irrelevant on windows.

**Comment by ewjoachim** [comment]
For the future, feel free to use triple backticks (```) to hightlight codeblocks rather than single backticks (`) on every line, this will make your reports more readable :)
