### ISSUE TITLE
Improve cli defer syntax

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/procrastinate#66]
Current syntax is
```
procrastinate defer dotted.path.to.task '{"json": "arguments"}'
```

I'm thinking:
```
procrastinate defer dotted.path.to.task json=arguments
```
Task argument and defer parameters would be recognized through the face defer parameters are flags with `--`, `-` not being a valid python identifier (though it could be passed as **kwargs but...).

But then how to do typing ?
I'm not sure the solutions we used for the similar problem in https://github.com/peopledoc/vault-cli apply here. And I'd like to avoid yaml here, because it's nowhere else in the project.
Interestingly, ansible has the same problem with -e and it's a mess.

- I'd like explicit strings, like `json="arguments"` (so all values right of equal would be passed to `json.loads()` but double quotes are going to be eaten by bash.
- But we could document that it's necessary to wrap double quotes in simple quotes.
- We could use the task type annotations but it really feels dangerous.
We could type variables (https://github.com/scrapy/scrapy/issues/356#issuecomment-26299069) (read the rest of the ticket)
- Or we could stay with json.
- Finally, we could have multiple ways, as long as it's not complexifying the code too much. A json for complex cases, simple keypairs for the rest (but like, I can live without lists, but bools and ints should be 1st class citizens)

Interesing reads:
- AWS: https://docs.aws.amazon.com/fr_fr/cli/latest/userguide/cli-usage-parameters.html#cli-usage-parameters-json
- Everything from https://www.google.com/search?q=cli+arguments+json

Any idea ?

**Comment by ewjoachim** [comment]
I'm tempted to go with `key=<json value>` so:
- `key=true`
- `key="string"`
- `key=1`

**Comment by mgu** [comment]
I don't really like `'key="string"'`  (with mandatory double quotes). I don't know if we could have some basic type coercion.

But I like the simplicity of `key=value` :)

**Comment by ewjoachim** [comment]
the problem with key=value is when value is `true` or `null` or `1`, it's ambiguous.

**Comment by mgu** [comment]
I really don't like the `'key="string"'` :)
The current syntax is simple to remember even if it's quite difficult to read a json string on the command-line.
(and I agree that we don't want to reproduce the `-e` behavior of ansible ;) )

**Comment by ewjoachim** [comment]
The other solution being:
```
a=yay (identical to a:str=yay)
a:bool=true
a:int=3
a:null=null
a:float=3.4
```

Not sure either.
We can keep json, but it's a solution hard to read AND write. It's sole advantage it it's easier for machines.

**Comment by mgu** [comment]
as we can't find a solution that we like, the best is to close this issue and keep the current syntax :)
