### ISSUE TITLE
Retry depending on the exception

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/procrastinate#84]
1. The retry strategy should be provided the exception that triggers the retry
2. A builtin mechanism should allow to retry only if the exception is of a given type or among a few types.

**Comment by ewjoachim** [comment]
I think the work on this ticket has been started by someone. Let's give them a shot before implementing this ticket.

**Comment by vhotz** [comment]
Yes, I take this issue and will do a PR once it's done.

**Comment by ewjoachim** [comment]
Assigning to let people know it's taken, but feel free to de-assign yourself if at some point you change your mind. It's your choice, your time, your call :)

**Comment by ewjoachim** [comment]
We're going to try implementing it on our side too :)
