### ISSUE TITLE
Add a very simple cron mechanism

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/procrastinate#85]
I'm being told the project would be easier to use if we provided a simple cron-like process. It might be interesting to look.

@EliotBerriot, you mentionned you were maybe interested to try a contribution ?

**Comment by EliotBerriot** [comment]
Yep, I can definitely have a look!

My initial idea, to keep this simple, was to have a separate, optionnal process, similar to `celery beat` scheduler.This process would be responsible to insert jobs in the database whenever the configured crontabs are matched. These jobs would be processed as usual, by regular workers.

For the cron-logic itself, if we're open to using dependencies, https://github.com/dbader/schedule looks like a pretty solid choice, meaning we'd only have to implement the configuration and job insertion logic.

There would'nt be any catchup mecanism: if the scheduler is down, upon restart, all missed tasked would simply be ignored.

If that sounds good to you, I can try to submit a PR this week :)

**Comment by ewjoachim** [comment]
👍 for me, @mgu a second opinion ?

**Comment by ewjoachim** [comment]
Does schedule 

I could see a 2nd decorator on tasks, like
```python
@app.schedule.every().day
@app.task(...)
def bla():
	pass
```
(if you don't call the `.do(job)` in the decorator, you allow procrastinate to do it itself with the job of its choice, i.e. a specialized `defer` function.)

(OR a global configuration, but then not sure what it should look like. Do you think people may want to control Cron tasks with configuration rather than code ? I honnestly don't know. All I know is that Celery does both.)

I'd say you probably need to raise if a cron task has parameters. Or require it accepts a single `CronContext` argument or something.

**Comment by pmourlanne** [comment]
We don't *have* to insert the jobs when they need to be run. We could take advantage of the `job.scheduled_at` column :o

This is just food for thought, your solution looks good :)

**Comment by mgu** [comment]
I don't like the idea of implementing a cron-like (or celery beat). I don't understand this need as we could already use cron/systemd.timers or something else that already exists.

**Comment by EliotBerriot** [comment]
>  I don't really understand this need as we could already use cron/systemd.timers or something else that already exists.

@mgu maybe I can elaborate on my use case then :)

For Funkwhale, we have potentially dozens or hundreds of separate installations of the software. Some of these are deployed by people with little to no sysadmin knowledge. 

In that context, it's really, really easier to ask them to setup a service with one command, `celery beat` than setting up a dozen cron jobs or services, especially since the list of scheduled job can change with each version ;)
